
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/1/9 10:52
---

local hstring = require("core.hstring");

local function printStr(name, val)
    print(name, "'"..tostring(val).."'")
end

local str = " typedef struct Student {";
local hs = hstring.newHString(str)
hs.skipSpace();
print("1 after skipSpace: ", "'"..hs.toString().."'")
assert(#(hs.toString()) == #str - 1)

local word;
hs.save();
word = hs.nextWord()
printStr("word: ", word)
hs.skipSpace();
word = hs.nextWord()
printStr("word: ", word)
hs.skipSpace();
word = hs.nextWord()
printStr("word: ", word)
hs.restore()

assert(#(hs.toString()) == #str - 1)
hs.save();
local words = hs.nextWords(3)
assert(#words == 3)
assert(words[1] == "typedef")
assert(words[2] == "struct")
assert(words[3] == "Student")
hs.restore()

assert(hs.startsWith("typedef"))
assert(hs.requireChar("t"))